ALTER TABLE requests ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'OPEN';
ALTER TABLE requests ADD COLUMN priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE requests ADD COLUMN category VARCHAR(20) NOT NULL DEFAULT 'OTHER';
